# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '//10.99.1.12/ ˝¬ÎµÁ”∞/¡Ÿ ±Ωªªª/08ºº ı/∏ˆ»ÀŒƒº˛º–/Hª∆Àß/adv5/AdvancedSkeleton5/AdvancedSkeleton5Files/icons/faceOptimize.ui'
#
# Created: Tue Sep 27 11:47:38 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui,QtWidgets

class Ui_shuaiFaceOptimizeWin(object):
    def setupUi(self, shuaiFaceOptimizeWin):
        shuaiFaceOptimizeWin.setObjectName("shuaiFaceOptimizeWin")
        shuaiFaceOptimizeWin.resize(250, 437)
        shuaiFaceOptimizeWin.setMinimumSize(QtCore.QSize(250, 437))
        self.centralwidget = QtWidgets.QWidget(shuaiFaceOptimizeWin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.selectAll_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.selectAll_checkBox.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectAll_checkBox.setFont(font)
        self.selectAll_checkBox.setChecked(True)
        self.selectAll_checkBox.setObjectName("selectAll_checkBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 39, 211, 271))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.shuaiChangeCtrls_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiChangeCtrls_checkBox.setGeometry(QtCore.QRect(10, 0, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiChangeCtrls_checkBox.setFont(font)
        self.shuaiChangeCtrls_checkBox.setChecked(True)
        self.shuaiChangeCtrls_checkBox.setObjectName("shuaiChangeCtrls_checkBox")
        self.addTougueCtrls_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.addTougueCtrls_checkBox.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addTougueCtrls_checkBox.setFont(font)
        self.addTougueCtrls_checkBox.setChecked(True)
        self.addTougueCtrls_checkBox.setObjectName("addTougueCtrls_checkBox")
        self.shuaiEyeBallCtrls_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiEyeBallCtrls_checkBox.setGeometry(QtCore.QRect(10, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiEyeBallCtrls_checkBox.setFont(font)
        self.shuaiEyeBallCtrls_checkBox.setChecked(True)
        self.shuaiEyeBallCtrls_checkBox.setObjectName("shuaiEyeBallCtrls_checkBox")
        self.shuaiAddScaleConstraint_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiAddScaleConstraint_checkBox.setGeometry(QtCore.QRect(10, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiAddScaleConstraint_checkBox.setFont(font)
        self.shuaiAddScaleConstraint_checkBox.setChecked(True)
        self.shuaiAddScaleConstraint_checkBox.setObjectName("shuaiAddScaleConstraint_checkBox")
        self.shuaiLockAndHideVisibility_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiLockAndHideVisibility_checkBox.setGeometry(QtCore.QRect(10, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiLockAndHideVisibility_checkBox.setFont(font)
        self.shuaiLockAndHideVisibility_checkBox.setChecked(True)
        self.shuaiLockAndHideVisibility_checkBox.setObjectName("shuaiLockAndHideVisibility_checkBox")
        self.optimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.optimizeButton.setGeometry(QtCore.QRect(20, 340, 211, 61))
        self.optimizeButton.setStyleSheet("font: 75 22pt \"Aharoni\";")
        self.optimizeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/advOptimize1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optimizeButton.setIcon(icon)
        self.optimizeButton.setIconSize(QtCore.QSize(171, 61))
        self.optimizeButton.setObjectName("optimizeButton")
        shuaiFaceOptimizeWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(shuaiFaceOptimizeWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 23))
        self.menubar.setObjectName("menubar")
        shuaiFaceOptimizeWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(shuaiFaceOptimizeWin)
        self.statusbar.setObjectName("statusbar")
        shuaiFaceOptimizeWin.setStatusBar(self.statusbar)

        self.retranslateUi(shuaiFaceOptimizeWin)
        QtCore.QMetaObject.connectSlotsByName(shuaiFaceOptimizeWin)

    def retranslateUi(self, shuaiFaceOptimizeWin):
        shuaiFaceOptimizeWin.setWindowTitle(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "ADVË°®ÊÉÖ‰ºòÂåñÈÄâÈ°πËÆæÁΩÆ", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "‰ºòÂåñÈÄâÈ°π", None, QtWidgets.QApplication.UnicodeUTF8))
        self.selectAll_checkBox.setText(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "ÂÖ®ÈÄâ", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiChangeCtrls_checkBox.setText(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "Â∞ÜÊõ≤Èù¢ÊéßÂà∂Âô®ËΩ¨Êç¢ÊàêÊõ≤Á∫ø", None, QtWidgets.QApplication.UnicodeUTF8))
        self.addTougueCtrls_checkBox.setText(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "Ê∑ªÂä ËàåÂ§¥ÊéßÂà∂Âô®", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiEyeBallCtrls_checkBox.setText(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "Ê∑ªÂä ÁúºÁêÉÊéßÂà∂Âô®", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiAddScaleConstraint_checkBox.setText(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "Ê∑ªÂä Áº©ÊîæÁ∫¶Êùü", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiLockAndHideVisibility_checkBox.setText(QtWidgets.QApplication.translate("shuaiFaceOptimizeWin", "ÈîÅÂÆöÈöêËóèvisbilityÂ±ûÊÄß", None, QtWidgets.QApplication.UnicodeUTF8))

import icons1_rc
