# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:/hq_tool/Maya/hq_maya/scripts/adv5/AdvancedSkeleton5/AdvancedSkeleton5Files/icons/optimize.ui'
#
# Created: Tue Apr 11 17:09:59 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui,QtWidgets

class Ui_shuaiAdvOptimizeWin(object):
    def setupUi(self, shuaiAdvOptimizeWin):
        shuaiAdvOptimizeWin.setObjectName("shuaiAdvOptimizeWin")
        shuaiAdvOptimizeWin.resize(250, 437)
        shuaiAdvOptimizeWin.setMinimumSize(QtCore.QSize(250, 437))
        self.centralwidget = QtWidgets.QWidget(shuaiAdvOptimizeWin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.selectAll_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.selectAll_checkBox.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectAll_checkBox.setFont(font)
        self.selectAll_checkBox.setChecked(False)
        self.selectAll_checkBox.setObjectName("selectAll_checkBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 39, 211, 271))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.shuaiChangeRootCtrl_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiChangeRootCtrl_checkBox.setGeometry(QtCore.QRect(10, 0, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiChangeRootCtrl_checkBox.setFont(font)
        self.shuaiChangeRootCtrl_checkBox.setChecked(True)
        self.shuaiChangeRootCtrl_checkBox.setObjectName("shuaiChangeRootCtrl_checkBox")
        self.shuaiGroupAndRename_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiGroupAndRename_checkBox.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiGroupAndRename_checkBox.setFont(font)
        self.shuaiGroupAndRename_checkBox.setChecked(True)
        self.shuaiGroupAndRename_checkBox.setObjectName("shuaiGroupAndRename_checkBox")
        self.shuaiLockHideAttr_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiLockHideAttr_checkBox.setGeometry(QtCore.QRect(10, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiLockHideAttr_checkBox.setFont(font)
        self.shuaiLockHideAttr_checkBox.setChecked(True)
        self.shuaiLockHideAttr_checkBox.setObjectName("shuaiLockHideAttr_checkBox")
        self.chenXi_Optimize_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.chenXi_Optimize_checkBox.setGeometry(QtCore.QRect(10, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chenXi_Optimize_checkBox.setFont(font)
        self.chenXi_Optimize_checkBox.setChecked(True)
        self.chenXi_Optimize_checkBox.setObjectName("chenXi_Optimize_checkBox")
        self.cc_spine2_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.cc_spine2_checkBox.setGeometry(QtCore.QRect(10, 80, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cc_spine2_checkBox.setFont(font)
        self.cc_spine2_checkBox.setChecked(True)
        self.cc_spine2_checkBox.setObjectName("cc_spine2_checkBox")
        self.shuaiAddSwivelFootAttr_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiAddSwivelFootAttr_checkBox.setGeometry(QtCore.QRect(10, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiAddSwivelFootAttr_checkBox.setFont(font)
        self.shuaiAddSwivelFootAttr_checkBox.setStyleSheet("")
        self.shuaiAddSwivelFootAttr_checkBox.setChecked(True)
        self.shuaiAddSwivelFootAttr_checkBox.setObjectName("shuaiAddSwivelFootAttr_checkBox")
        self.shuaiFixFinggerDriven_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiFixFinggerDriven_checkBox.setGeometry(QtCore.QRect(10, 120, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiFixFinggerDriven_checkBox.setFont(font)
        self.shuaiFixFinggerDriven_checkBox.setStyleSheet("")
        self.shuaiFixFinggerDriven_checkBox.setChecked(True)
        self.shuaiFixFinggerDriven_checkBox.setObjectName("shuaiFixFinggerDriven_checkBox")
        self.shuaiRotateCtrls_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiRotateCtrls_checkBox.setGeometry(QtCore.QRect(10, 140, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiRotateCtrls_checkBox.setFont(font)
        self.shuaiRotateCtrls_checkBox.setStyleSheet("")
        self.shuaiRotateCtrls_checkBox.setChecked(True)
        self.shuaiRotateCtrls_checkBox.setObjectName("shuaiRotateCtrls_checkBox")
        self.shuaiAddShowModAttr_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiAddShowModAttr_checkBox.setGeometry(QtCore.QRect(10, 160, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiAddShowModAttr_checkBox.setFont(font)
        self.shuaiAddShowModAttr_checkBox.setStyleSheet("")
        self.shuaiAddShowModAttr_checkBox.setChecked(True)
        self.shuaiAddShowModAttr_checkBox.setObjectName("shuaiAddShowModAttr_checkBox")
        self.shuaiFixConstraint_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiFixConstraint_checkBox.setEnabled(True)
        self.shuaiFixConstraint_checkBox.setGeometry(QtCore.QRect(10, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiFixConstraint_checkBox.setFont(font)
        self.shuaiFixConstraint_checkBox.setStyleSheet("")
        self.shuaiFixConstraint_checkBox.setChecked(False)
        self.shuaiFixConstraint_checkBox.setObjectName("shuaiFixConstraint_checkBox")
        self.shuaiFixCharacterScale_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.shuaiFixCharacterScale_checkBox.setEnabled(True)
        self.shuaiFixCharacterScale_checkBox.setGeometry(QtCore.QRect(10, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shuaiFixCharacterScale_checkBox.setFont(font)
        self.shuaiFixCharacterScale_checkBox.setAcceptDrops(False)
        self.shuaiFixCharacterScale_checkBox.setStyleSheet("")
        self.shuaiFixCharacterScale_checkBox.setChecked(True)
        self.shuaiFixCharacterScale_checkBox.setTristate(False)
        self.shuaiFixCharacterScale_checkBox.setObjectName("shuaiFixCharacterScale_checkBox")
        self.optimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.optimizeButton.setGeometry(QtCore.QRect(20, 340, 211, 61))
        self.optimizeButton.setStyleSheet("font: 75 22pt \"Aharoni\";")
        self.optimizeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/advOptimize1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optimizeButton.setIcon(icon)
        self.optimizeButton.setIconSize(QtCore.QSize(171, 61))
        self.optimizeButton.setObjectName("optimizeButton")
        shuaiAdvOptimizeWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(shuaiAdvOptimizeWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 23))
        self.menubar.setObjectName("menubar")
        shuaiAdvOptimizeWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(shuaiAdvOptimizeWin)
        self.statusbar.setObjectName("statusbar")
        shuaiAdvOptimizeWin.setStatusBar(self.statusbar)

        self.retranslateUi(shuaiAdvOptimizeWin)
        QtCore.QMetaObject.connectSlotsByName(shuaiAdvOptimizeWin)

    def retranslateUi(self, shuaiAdvOptimizeWin):
        shuaiAdvOptimizeWin.setWindowTitle(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "ADV身体优化选项设置", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "优化选项", None, QtWidgets.QApplication.UnicodeUTF8))
        self.selectAll_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "全选", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiChangeRootCtrl_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "修改Root_M控制器形状", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiGroupAndRename_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "调整大组层级关系", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiLockHideAttr_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "锁定隐藏用不到的属性", None, QtWidgets.QApplication.UnicodeUTF8))
        self.chenXi_Optimize_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "调整胯部控制方式", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cc_spine2_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "调整身体FK控制方式", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiAddSwivelFootAttr_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "脚IK添加swivel_foot属性", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiFixFinggerDriven_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "修正手指驱动左右不对称", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiRotateCtrls_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "修正控制器方向", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiAddShowModAttr_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "添加showMod属性", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiFixConstraint_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "修改骨骼约束", None, QtWidgets.QApplication.UnicodeUTF8))
        self.shuaiFixCharacterScale_checkBox.setText(QtWidgets.QApplication.translate("shuaiAdvOptimizeWin", "修复Character控制器缩放", None, QtWidgets.QApplication.UnicodeUTF8))

import icons1_rc
